CREATE TABLE REGISTERINFO02 (
    USERNAME   VARCHAR2(8)    NOT NULL,
    EMAIL      VARCHAR2(30)  NOT NULL,
    PASSWORD   VARCHAR2(16)  NOT NULL,
    AGE        VARCHAR2(3)   NOT NULL,
    BIRTHDAY   VARCHAR2(10)  NOT NULL,
    DELFLG     CHAR(1)       NOT NULL
);
ALTER TABLE REGISTERINFO02 MODIFY DELFLG DEFAULT '0';